<div id="mainOffers">
    <div class="offerSection" id="grandReserveSection">
        <h3>
            <span class="new">New!</span>
            Grand Reserve
            <br />
            Collection
        </h3>
        <a href="/e-liquid-cartridges/reserve-collection/grand-reserve/" class="btn-link-full offer-img-link">
            <img src="/skin/frontend/default/vaporfi_theme/images/img-grand-reserve-home-offer.jpg" alt="Grand Reserve Collection" width="284" height="152" />
        </a>
        <h4>Award winning refined flavors for refined vapers</h4>
        <a href="/e-liquid-cartridges/reserve-collection/grand-reserve/" class="greenButtonSml" style="width:130px;">shop now</a>
        <div class="offerSectionBottom"></div>
    </div>
    <div class="offerSection">
        <h3>
            New
            <span>VOX 100</span>
            TC
        </h3>
        <a href="#" class="btn-link-full offer-img-link">
            <img src="/skin/frontend/default/vaporfi_theme/images/img-vox-100-tc-home-offer.jpg" alt="VOX 100 TC" width="284" height="152" />
        </a>
        <h4>Vox 100 TC Now Available</h4>
        <p>About as advanced as it can get, Temperature Control + VOX 100W power! </p>
        <a href="#" class="greenButtonSml" style="width:130px;">Shop VOX 100 TC</a>
        <div class="offerSectionBottom"></div>
    </div>
    <div id="stepFlavorSection" class="offerSection last">
        <h3>Custom E-Liquids</h3>
        <div class="stepFlavor">
            <a href="/e-liquid-cartridges/custom-blending/">
                <img src="/skin/frontend/default/vaporfi_theme/images/mixing_step_1.png" alt="Choose Your Strength" width="51" height="50" />
            </a>
            <h4>Choose Your Strength</h4>
            <p>You pick the level of nicotine you want to vape.</p>
        </div>
        <div class="stepFlavor">
            <a href="/e-liquid-cartridges/custom-blending/">
                <img src="/skin/frontend/default/vaporfi_theme/images/mixing_step_2.png" alt="Choose Your Flavors" width="51" height="50" />
            </a>
            <h4>Choose Your Flavors</h4>
            <p>Mix and match up to three flavors from our huge list of tasty e-liquids.</p>
        </div>
        <div class="stepFlavor">
            <a href="/e-liquid-cartridges/custom-blending/">
                <img src="/skin/frontend/default/vaporfi_theme/images/mixing_step_3.png" alt="Enjoy The Freedom" width="51" height="50" />
            </a>
            <h4>We Make it Fresh</h4>
            <p>Our expert Vapetenders™ mix your blend fresh. No pre-packaged e-liquids here.</p>
        </div>
        <a href="/e-liquid-cartridges/custom-blending/" class="greenButtonSml" style="width:140px;">Start Blending</a>
        <div class="offerSectionBottom"></div>
    </div>
    <div class="clear"></div>
</div>





<div id="howitworks">
    <h2>How do vaporizers work?</h2>
    <p>E-cigarettes and vaporizers have taken the world by storm by allowing all the pleasures of traditional smoking without the bad breath, stinky clothes, tremendous cost, and harmful effects of tobacco.</p>
    <a href="#" class="greenButton" id="howitworks-link">Read More</a>
</div>
<img src="/skin/frontend/default/vaporfi_theme/images/how_it_works_img_1.png" id="howitworksImg" width="469" height="339" />
<div class="boxBottom1"></div>





<div id="testimonial1">
    <p>“I cannot speak highly enough about these awesome products from VaporFi. I had wanted to get into better e-cigarette models for a while, and in doing my research I learned about this company. It’s great to see this kind of performance; my enjoyment of vaping has increased 10-fold!”
        <a href="#">read more</a>
        <span>- Liz R. Dallas, TX</span>
    </p>
</div>
<div id="testimonial2">
    <p>“I am a vapor connoisseur, and these are top of the line. I am not only pleased with the selection of excellent battery models, but how powerful they all are. 2 thumbs up for the great flavors- not many brands out there give the option of blending them yourself, and this takes things to another level!”
        <a href="#">read more</a>
        <span>- David L. New York, NY</span>
    </p>
</div>
<img src="/skin/frontend/default/vaporfi_theme/images/testimonial_img_1.png" id="testimonialImg" width="211" height="201" />
<div class="clear"></div>
<div class="boxBottom1"></div>


<a href="#" class="btn-link-full">
    <img src="/skin/frontend/default/vaporfi_theme/images/banner_home_bottom_sample_3_pack.png" />
</a>
<div class="clear"></div>
<div class="boxBottom1"></div>


<div class="boxContentFullMain">
    <a href="javascript: void(0)" title="30 Day Money Back Guarantee" class="bottom-banner top pop-up-link" id="GuaranteePop">
        <img src="/skin/frontend/default/vaporfi_theme/images/moneyback-orange.png" width="450" height="150" alt="30 Day Money Back Guarantee">
    </a>
    <a href="#" title="VaporFi Gift Cards" class="bottom-banner top">
        <img src="/skin/frontend/default/vaporfi_theme/images/gift-card-banner.png" width="450" height="150" alt="VaporFi Gift Cards">
    </a>
    <a href="#" title="Why e-Liquid Rocks" class="bottom-banner">
        <img src="/skin/frontend/default/vaporfi_theme/images/eliquid-rocks-green.png" width="450" height="150" alt="Why e-Liquid Rocks">
    </a>
    <a href="#" title="Refer-A-Friend" class="bottom-banner">
        <img src="/skin/frontend/default/vaporfi_theme/images/refer-a-friend-banner.png" width="450" height="150" alt="Refer-A-Friend">
    </a>
    <div class="clear">&nbsp;</div>
</div>